# Generated by Django 3.0.4 on 2021-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20210703_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
