# Generated by Django 3.2.5 on 2021-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20210703_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path_image',
            field=models.FileField(upload_to='media', verbose_name='Изображение'),
        ),
    ]
