# Generated by Django 3.2.5 on 2021-07-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL Сайта')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL сайта')),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Телефон сайта')),
                ('time', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Часы работы')),
                ('adress', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Адресс компании')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email')),
                ('name_firm', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Название фирмы')),
                ('name_person', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ваше имя')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='FieldCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Расположение элемента')),
                ('value', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название поля')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.catalog')),
            ],
            options={
                'verbose_name': 'Поле каталога',
                'verbose_name_plural': 'Поля каталога',
            },
        ),
    ]
