# Generated by Django 3.0.4 on 2021-07-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210718_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
