# Generated by Django 3.2.5 on 2021-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210803_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.AddField(
            model_name='catalog',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
