# Generated by Django 3.2.5 on 2021-08-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210803_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='ключ')),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.company')),
            ],
        ),
    ]
