# Generated by Django 3.2.5 on 2021-08-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_fieldcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCompanyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='ключ')),
            ],
            options={
                'verbose_name': 'Ключ поля компании',
                'verbose_name_plural': 'Ключи поля компании',
            },
        ),
        migrations.CreateModel(
            name='FieldCompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.company')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.fieldcompanykey')),
            ],
            options={
                'verbose_name': 'Поле компании',
                'verbose_name_plural': 'Поля компании',
            },
        ),
        migrations.DeleteModel(
            name='FieldCompany',
        ),
    ]
