# Generated by Django 3.2.5 on 2021-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210813_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcompanykey',
            name='title',
            field=models.CharField(default='описание поля', max_length=30, verbose_name='название поля на русском'),
            preserve_default=False,
        ),
    ]
